/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 phantoms.glb --transform
*/

import React, { useRef,useLayoutEffect } from 'react'
import { useGLTF,useScroll } from '@react-three/drei'
import {useFrame} from '@react-three/fiber'
import gsap from 'gsap'

export function Robot(props) {
  const { nodes, materials } = useGLTF('./models/robot/chonky_cat_trio.glb')
  const robot = useRef()
  const scroll = useScroll()
  const tl = useRef()

  useFrame((state, delta)=>{
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useLayoutEffect(()=> {
    tl.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}})

    tl.current
    .to(robot.current.rotation, {y: -1}, 2)
    .to(robot.current.position, {x: 1}, 2)

    .to(robot.current.rotation, {y: 1}, 6)   
    .to(robot.current.position, {x: -1}, 6)

    .to(robot.current.rotation, {y: 0}, 11)
    .to(robot.current.rotation, {x: 1}, 11)
    .to(robot.current.position, {x: 0}, 11)

    .to(robot.current.rotation, {y: 0}, 13)
    .to(robot.current.rotation, {x: -1}, 13)    
    .to(robot.current.position, {x: 0}, 13)

    .to(robot.current.rotation, {y: 0}, 16)   
    .to(robot.current.rotation, {x: 0}, 16) 
    .to(robot.current.position, {x: 0}, 16)    

    .to(robot.current.rotation, {y: 0}, 20)   
    .to(robot.current.rotation, {x: 0}, 20) 
    .to(robot.current.position, {x: 0}, 20)   

  },[])
  
  return (
    <group {...props} dispose={null} ref={robot}>      
      <group position={[-0.21, 0.16, 0.37]} rotation={[0, 0, 0]} scale={0.15}>
      <mesh
          castShadow
          receiveShadow
          geometry={nodes.fat_cat_white_Cat01_0.geometry}
          material={materials.Cat01}
          position={[0, 0, 13.579]}
          scale={3.736}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fat_cat_white1_Cat02_0.geometry}
          material={materials.Cat02}
          position={[0, 0, 13.579]}
          scale={3.736}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fat_cat_white2_Cat03_0.geometry}
          material={materials.Cat03}
          position={[0, 0, 13.579]}
          scale={3.736}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube1_standardSurface1_0.geometry}
          material={materials.standardSurface1}
        />
      </group>
    </group>
  )
}

useGLTF.preload('./models/robot/chonky_cat_trio.glb')
